---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04

suites:
  - name: zookeeper
    run_list:
      - "java::default"
      - "zookeeper-config::default"
    attributes:
