---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - "java::default"
      - "cookbooks::default"
    attributes:
