---
Description: ExDataLab Zookeeper ASG Deployment
Parameters:
  VpcId:
    Description: VPC to deploy to
    Type: String
  AmiId:
    Description: AMI ID to launch in ASG
    Type: String
  AsgSubnets:
    Description: Subnets in which ASG should be hosted
    Type: CommaDelimitedList
  AsgSubnetAzs:
    Description: Availability zones in which ASG should be hosted
    Type: CommaDelimitedList
  KeyName:
    Description: EC2 key name to use for instances
    Type: String
  InstanceCount:
    Description: Number of instances to provision
    Type: String
    Default: 3
  MinInstancesInService:
    Description: Min ISR count for rolling updates
    Type: String
    Default: 1
  Subnet1:
    Description: Subnet for ENI 1
    Type: String
  Subnet2:
    Description: Subnet for ENI 2
    Type: String
  Subnet3:
    Description: Subnet for ENI 3
    Type: String
  PipelineInstanceId:
    Description: Pipeline instance ID
    Type: String
    Default: unspecified
  InstanceSecgroup:
    Description: Instance SecurityGroup
    Type: String
  InstanceType:
    Description: Instance SecurityGroup
    Type: String
    Default: t2.micro
Resources:
  NetworkInterface1:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId:
        Ref: Subnet1
      PrivateIpAddress: 172.31.1.100
      Description: ENI for ZK ID 1
      GroupSet:
      - Ref: InstanceSecgroup
      Tags:
      - Key: Name
        Value: ZOOKEEPER-1
  NetworkInterface2:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId:
        Ref: Subnet2
      PrivateIpAddress: 172.31.2.100
      Description: ENI for ZK ID 2
      GroupSet:
      - Ref: InstanceSecgroup
      Tags:
      - Key: Name
        Value: ZOOKEEPER-2
  NetworkInterface3:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId:
        Ref: Subnet3
      PrivateIpAddress: 172.31.3.100
      Description: ENI for ZK ID 3
      GroupSet:
      - Ref: InstanceSecgroup
      Tags:
      - Key: Name
        Value: ZOOKEEPER-3
  # InstanceSecgroup:
  #   Type: AWS::EC2::SecurityGroup
  #   Properties:
  #     GroupDescription: Enable SSH and required ports
  #     VpcId:
  #       Ref: VpcId
  #     SecurityGroupEgress:
  #     - IpProtocol: tcp
  #       FromPort: '53'
  #       ToPort: '53'
  #       CidrIp: 0.0.0.0/0
  #     - IpProtocol: tcp
  #       FromPort: '80'
  #       ToPort: '80'
  #       CidrIp: 0.0.0.0/0
  #     - IpProtocol: tcp
  #       FromPort: '443'
  #       ToPort: '443'
  #       CidrIp: 0.0.0.0/0
  #     - IpProtocol: tcp
  #       FromPort: '8300'
  #       ToPort: '8302'
  #       CidrIp: 0.0.0.0/0
  #     - IpProtocol: udp
  #       FromPort: '8300'
  #       ToPort: '8302'
  #       CidrIp: 0.0.0.0/0
  #     - IpProtocol: udp
  #       FromPort: '0'
  #       ToPort: '65535'
  #       CidrIp: 0.0.0.0/0
  #     - IpProtocol: tcp
  #       FromPort: '8089'
  #       ToPort: '8089'
  #       CidrIp: 10.193.215.40/32
  #     - IpProtocol: tcp
  #       FromPort: '9997'
  #       ToPort: '9997'
  #       CidrIp: 10.193.215.41/32
  #     - IpProtocol: tcp
  #       FromPort: '2888'
  #       ToPort: '2888'
  #       CidrIp: 10.0.0.0/0
  #     - IpProtocol: tcp
  #       FromPort: '3888'
  #       ToPort: '3888'
  #       CidrIp: 10.0.0.0/0
  #     - IpProtocol: tcp
  #       FromPort: '2181'
  #       ToPort: '2181'
  #       CidrIp: 10.0.0.0/0
  #     SecurityGroupIngress:
  #     - IpProtocol: tcp
  #       FromPort: '22'
  #       ToPort: '22'
  #       CidrIp: 0.0.0.0/0
  #     - IpProtocol: tcp
  #       FromPort: '8300'
  #       ToPort: '8302'
  #       CidrIp: 0.0.0.0/0
  #     - IpProtocol: udp
  #       FromPort: '8300'
  #       ToPort: '8302'
  #       CidrIp: 0.0.0.0/0
  #     - IpProtocol: tcp
  #       FromPort: '7071'
  #       ToPort: '7072'
  #       CidrIp: 0.0.0.0/0
  #     - IpProtocol: tcp
  #       FromPort: '2888'
  #       ToPort: '2888'
  #       CidrIp: 10.0.0.0/0
  #     - IpProtocol: tcp
  #       FromPort: '3888'
  #       ToPort: '3888'
  #       CidrIp: 10.0.0.0/0
  #     - IpProtocol: tcp
  #       FromPort: '2181'
  #       ToPort: '2181'
  #       CidrIp: 10.0.0.0/0
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: Zookeeper-Instance-Policy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - s3:*
            - cloudwatch:GetMetricStatistics
            - cloudwatch:ListMetrics
            - cloudwatch:PutMetricData
            - ec2:Describe*
            - ec2:List*
            - kms:Decrypt
            - kms:Get*
            - kms:List*
            - dynamodb:*
            - cloudformation:SignalResource
            - ec2:AttachVolume
            - ec2:CreateVolume
            - ec2:CreateTags
            - ec2:AttachNetworkInterface
            - ec2:DetachNetworkInterface
            - autoscaling:SetInstanceHealth
            Resource: "*"
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - Ref: InstanceRole
  InstanceAsg:
    Type: AWS::AutoScaling::AutoScalingGroup
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService:
          Ref: MinInstancesInService
        MaxBatchSize: 1
        PauseTime: PT10M
        WaitOnResourceSignals: true
    Properties:
      AvailabilityZones:
        Ref: AsgSubnetAzs
      LaunchConfigurationName:
        Ref: InstanceLc
      MaxSize:
        Ref: InstanceCount
      MinSize:
        Ref: InstanceCount
      Tags:
      - Key: Name
        Value:
          Ref: AWS::StackName
        PropagateAtLaunch: true
      - Key: Server_Function
        Value: Packer
        PropagateAtLaunch: true
      - Key: ECS:ServerFunction
        Value: Packer
        PropagateAtLaunch: true
      - Key: System
        Value: ExDataLab
        PropagateAtLaunch: true
      VPCZoneIdentifier:
        Ref: AsgSubnets
    CreationPolicy:
      AutoScalingCreationPolicy:
        # MinSuccessfulInstancesPercent: 100
        MinSuccessfulInstancesPercent: 0
      ResourceSignal:
        Count: 3
        Timeout: PT30M
  InstanceLc:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: false
      IamInstanceProfile:
        Ref: InstanceProfile
      ImageId:
        Ref: AmiId
      InstanceMonitoring: true
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: KeyName
      SecurityGroups:
      - Ref: InstanceSecgroup
      UserData:
        Fn::Base64:
          Fn::Join:
          - ''
          - - ''
            - "#!/bin/bash -e\n"
            - "echo 'hello from userdata'\n"
            - "sudo bash /usr/local/bin/zk_run.sh\n"
            - 'echo "hello userdata - running by $(whoami)"'
            - "\n"
            - "cfn-signal -e 0 --stack "
            - Ref: AWS::StackName
            - " --resource InstanceAsg "
            - " --region "
            - Ref: AWS::Region
            - "\n"
Outputs:
  NetworkInterfaceIp1:
    Value:
      Fn::GetAtt:
      - NetworkInterface1
      - PrimaryPrivateIpAddress
  NetworkInterfaceIp2:
    Value:
      Fn::GetAtt:
      - NetworkInterface2
      - PrimaryPrivateIpAddress
  NetworkInterfaceIp3:
    Value:
      Fn::GetAtt:
      - NetworkInterface3
      - PrimaryPrivateIpAddress
  Environment:
    Description: Environment launched into
    Value: ExDataLab
  PipelineInstanceId:
    Description: Pipeline instance ID
    Value:
      Ref: PipelineInstanceId
AWSTemplateFormatVersion: '2010-09-09'
